### ISSUE TITLE
irregular grids not working?

### ISSUE THREAD

**Issue by floswald** [floswald/ApproXD.jl#2]
message from @nilshg:

> I just wanted to quickly get back to the point about irregular grids in ApproXD; I put together a comparison of some interpolation approaches in Julia and it appears that the irregular grid in ApproXD is not working as expected. 
If you have five minutes you can check out my code at https://github.com/nilshg/LearningModels/blob/master/Test_Interpolations.jl, maybe there's an error in how I'm using ApproXD (although the linear interpolation on a regular grid gives the same results as that of Grid.jl, so I think I'm doing it correctly).

**Comment by floswald** [comment]
Hi @nilshg,

thanks for looking into that. I looked at your code, I suspect the linear interpolation is "wrong" because you want to approximate a non-linear function. I added a test on irregularly spaced grids, and it passes: https://travis-ci.org/floswald/ApproXD.jl/builds/51810505

So I would conclude that there is nothing wrong with the library. The fact that a linear approx does poor on a non-linear function is clear. 

you can look at the test here: https://github.com/floswald/ApproXD.jl/blob/master/test/test_lininterp.jl#L767

**Comment by nilshg** [comment]
Hi @floswald,

Thanks for getting back to me on this. I have to apologize for the confusion - after reading your message I went back to recreate a simpler version of what went wrong with my code only to find that I overlooked a stupid mistake in the code that caused the bad approximation with ApproXD on the irregular grid. Basically, I mistakenly approximated the function evaluated on the regular grid using the irregularly spaced grid points, so there was no way for the results to get close to the true values.

I have since amended my code (see [commit](https://github.com/nilshg/LearningModels/commit/ed09f3b68c75c9b8c2c779a3db7b6d8d9366455e)) and ApproXD is now performing as well as expected:

````
∑|f(x)-f(x_int)/f(x)|/n in 1 dimension
	Grid (linear): 0.007
	Grid (quadratic): 0.010
	ApproXD (linear): 0.007
	ApproXD (linear, irregular grid): 0.000
	Dierckx (spline): 0.005
	Dierckx (spline, irregular grid): 0.000
	NumericalMath(pchip): 0.003

∑|f(x)-f(x_int)/f(x)|/n in 2 dimensions
	Grid (linear): 0.012
	Grid (quadratic): 0.019
	ApproXD (linear): 0.012
	ApproXD (linear, irregular grid): 0.003
	Dierckx (spline): 0.006
	Dierckx (spline, irregular grid): 0.000
````

**Comment by floswald** [comment]
Awesome!

File that under "gains from communication". I'm glad it works for you now.
